### ISSUE TITLE
Missing: metallb-ingress-service.yaml

### ISSUE THREAD

**Issue by tradenet** [AdnanHodzic/wp-k8s#1]
Hello,
Trying to follow you raspberry pi configuration.
as per: 
https://foolcontrol.org/?p=4004
I see this yaml file is missing:
https://github.com/AdnanHodzic/wp-k8s/blob/main/metallb-ingress-service.yaml

**Comment by AdnanHodzic** [comment]
Ah, good catch. While the file is still there, I had it renamed to[ metallb.yaml](https://github.com/AdnanHodzic/wp-k8s/blob/main/metallb.yaml). 

Also updated the blog post.

**Comment by tradenet** [comment]
> Ah, good catch. While the file is still there, I had it renamed to[ metallb.yaml](https://github.com/AdnanHodzic/wp-k8s/blob/main/metallb.yaml).
> 
> Also updated the blog post.

I am bit confused now as in kustomization.yaml you say:
`resources: 
  #- Enable/uncomment if using RPI or any other setup then public cloud
  #- metallb-ingress-service.yaml
`
And you also set a custom address pool. Somewhat confusing as well.
I am using RPI. Would there be a difference?

Thanks.

**Comment by AdnanHodzic** [comment]
I just pushed changes which should clarify this a bit more.

```
# Enable/uncomment if using RPI or any other setup other then public cloud
  # Reference: https://microk8s.io/docs/addon-metallb
  - metallb.yaml
 ```
 
 Not how much clearer could this be at this point, which means it has to be enabled if you're using RPI :) 
 
 > And you also set a custom address pool. Somewhat confusing as well.

Also updated this section of metallb.yaml

```
  # Reference: "Step 4.7: Enable and configure MetalLB" https://foolcontrol.org/?p=4004
  # Must match initial node pool configured as part of: "Step 3.10: Comment existing contents and add static configuration"
  - 192.168.1.1-192.168.1.100
```

It's not a custom address pool, it's the same pool I configured all my nodes in and IP's I mentioned my nodes were part of.

**Comment by tradenet** [comment]
Ok got it. Nice project BTW. I am not using Synology but my own OMV build with a ZFS pool of drives that I managed to create a NFS PVC with the cluster using NFS CI Storage Class. It's actually working. On the same machine I have Mariadb in docker. So it will be interesting to see how it all comes together. Thanks!

**Comment by AdnanHodzic** [comment]
Good to hear! Yes, it's definitely working, https://foolcontrol.org & https://atuf.app &  (other non publicly exposed workloads) are all being hosted on my private RPI cluster. 

As I stated in blog post "* Synology DS920+ NAS (optional)" section, for NFS I created a project which could be used instead: https://github.com/AdnanHodzic/nfs-server-k8s and I explained how to create MySQL cluster using the operator: https://github.com/AdnanHodzic/wp-k8s#howto-create-mysql-cluster-using-mysql-operator
